### ISSUE TITLE
Show (pretty and) helpful error messages, if any

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/miniChRIS#1]
- [x] during startup
- [x] if any plugins could not be added

**Comment by lumuchris256** [comment]
hi @jennydaman is this issue still relevant ?
i would want to take a spin on

**Comment by jennydaman** [comment]
Thanks for visiting this issue. It's somewhat obsolete now, the heavy-lifting is now done by pure docker-compose and [chrisomatic](https://github.com/FNNDSC/chrisomatic).

@lumuchris256 are you interested in infrastructure, backend, containers, etc? You could try contributing to chrisomatic, or try creating `miniChRIS` using Kubernetes or OKD instead of docker-compose. These would all be very cool but very involved, let me know and I'd be happy to guide you.

**Comment by lumuchris256** [comment]
> Thanks for visiting this issue. It's somewhat obsolete now, the heavy-lifting is now done by pure docker-compose and [chrisomatic](https://github.com/FNNDSC/chrisomatic).
> 
> @lumuchris256 are you interested in infrastructure, backend, containers, etc? You could try contributing to chrisomatic, or try creating `miniChRIS` using Kubernetes or OKD instead of docker-compose. These would all be very cool but very involved, let me know and I'd be happy to guide you.

@jennydaman thanks for the pointers am more into the react typescript frameworks 
but okay to jump in finding the way around  creating minichris using kubernetes (i have some background in CI deployment with docker)
With a few pointers i can also ably go on with chrisomatic
the only blocker would be the given  limited time to do final application for outreachy with ChRIS project
other issue i need your confirmation https://github.com/FNNDSC/ChRIS_store_ui/issues/152

**Comment by jennydaman** [comment]
Fixed by https://github.com/FNNDSC/chrisomatic
