### ISSUE TITLE
Log aggregation

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/miniChRIS#10]
Aggregation and parsing of the backend microservice logs would make it easier for developers and sysadmins to troubleshoot errors.

The buzzword "Kibana" should be a good starting point to research.

### Prereqs:

Backend service such as django (chris), celery (chris_worker and worker_periodic),  pman, and pfcon do logging all in different ways.

- [ ] https://github.com/FNNDSC/pfcon/issues/132
- [ ] https://github.com/FNNDSC/pman/issues/213
- [ ] https://github.com/FNNDSC/ChRIS_ultron_backEnd/issues/443

**Comment by kibablu** [comment]
@jennydaman I'm trying to research this and let's see if I can get anywhere near. I will ping you with any updates:crossed_fingers:

**Comment by kibablu** [comment]
@jennydaman I have made progressive research on Kibana, we can use Elasticsearch to search logs and Kibana to visualize our logs.
I will try to come up with an example

**Comment by sakshi1215** [comment]
> @jennydaman I have made progressive research on Kibana, we can use Elasticsearch to search logs and Kibana to visualize our logs.
> I will try to come up with an example

You first need a log aggregator something like fluentd or loki before you can go ahead & dump the logs to Kibana instance which is then picked up the elasticsearch to index & query them.

**Comment by kibablu** [comment]
@sakshi1215 you're right, it is commented out [here ](https://github.com/FNNDSC/miniChRIS-docker/blob/160b47911934d07aa80b16f269dae65a279c8447/docker-compose.yml#L315)

**Comment by sakshi1215** [comment]
> @sakshi1215 you're right, it is commented out [here](https://github.com/FNNDSC/miniChRIS-docker/blob/160b47911934d07aa80b16f269dae65a279c8447/docker-compose.yml#L315)

That is a very naive installation of only the docker image, we need to make sure of the scrape targets before we can actually start utilising any log aggregator.

**Comment by Zainab-ik** [comment]
Hi @jennydaman, I am an outreachy applicant. Can you assign this issue to me and give me an insight into what should be done?
Thank you.

From my understanding, the last task is to see your output while running which is the log instead of getting the output in a file.

**Comment by jennydaman** [comment]
@Zainab-ik thanks for your interest in this issue! This is not a simple feature, I would suggest you have a strong background with containers and docker-compose.

First, some background: the "ChRIS backend" is not a single server, but rather a set of services and microservices, which may even be deployed on different clouds. These services include CUBE, celery, rabbitmq, PostgreSQL, pfcon, pman, just to name a few. This fragmentation has its advantages, such as being able to scale or upgrade components individually, however there is a problem: let's say you encounter an error, how do you trace it to find its cause? You'll have to check the container logs for each service individually.

To organize this increasingly complicated mess, in this issue I am proposing we use the "ELK stack" to provide log aggregation. ELK stands for ElasticSearch, LogStash, and Kibana. We can use these services to provide a friendly user interface to browsing and searching the logs from all of the ChRIS backend services at once.

**Comment by jennydaman** [comment]
A solution to this issue would be to add services to docker-compose.yml and configuration files to this repository which configure ELK (or the OpenSearch forks) to do log aggregation of the ChRIS backend services.

**Comment by Zainab-ik** [comment]
> @Zainab-ik thanks for your interest in this issue! This is not a simple feature, I would suggest you have a strong background with containers and docker-compose.
> 
> First, some background: the "ChRIS backend" is not a single server, but rather a set of services and microservices, which may even be deployed on different clouds. These services include CUBE, celery, rabbitmq, PostgreSQL, pfcon, pman, just to name a few. This fragmentation has its advantages, such as being able to scale or upgrade components individually, however there is a problem: let's say you encounter an error, how do you trace it to find its cause? You'll have to check the container logs for each service individually.
> 
> To organize this increasingly complicated mess, in this issue I am proposing we use the "ELK stack" to provide log aggregation. ELK stands for ElasticSearch, LogStash, and Kibana. We can use these services to provide a friendly user interface to browsing and searching the logs from all of the ChRIS backend services at once.

@jennydaman, Thanks. I have a basic understanding and containers and dockers. So I'd like to give it a try.

**Comment by Zainab-ik** [comment]
> A solution to this issue would be to add services to docker-compose.yml and configuration files to this repository which configure ELK (or the OpenSearch forks) to do log aggregation of the ChRIS backend services.

@jennydaman, I'd do research about this and update you.
