### ISSUE TITLE
Visualize cAdvisor data via prometheus in Grafana

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/miniChRIS#12]
We are interested in metrics such as the peak memory usage, CPU efficiency, ..., of ChRIS plugins.

A feature proposed to pman might make this easier: https://github.com/FNNDSC/pman/issues/215

**Comment by sakshi1215** [comment]
@jennydaman I checked the branch & looks like you have already installed the prometheus & cAdvisor image, and have configured the scrape_config. What is the requirement for this? Do we need dashbaord visualisation of them or is the configuration not working correctly?

**Comment by jennydaman** [comment]
@sakshi1215 I have configured them to run in docker-compose but I have not gotten around to writing any dashboard visualizations for them. I would be interested in being able to visualize things like

- how much memory is being used on average by ChRIS plugins?
- which ChRIS plugins are most memory-hungry?
- what is the CPU efficiency of the ChRIS plugin pl-fshack?
- ...

I believe these can be accomplished using cAdvisor and prometheus. The task here is to develop dashboard visualizations which can answer these kinds of questions.

It might be easier to solve this if https://github.com/FNNDSC/pman/issues/215 is first satisfied.
