### ISSUE TITLE
Allow for plugins to install be requested via input argument to Github Actions

### ISSUE THREAD

**Issue by jennydaman** [FNNDSC/miniChRIS#2]

**Comment by somya51p** [comment]
@jennydaman please assign me this issue.

**Comment by jennydaman** [comment]
Sure thing. I'm imagining that this can be done by generating `chrisomatic.yml` on-the-fly. Let me know if you would like guidance.

**Comment by jennydaman** [comment]
@somya51p, are you working on this issue simultaneously with other issues?

@sherrif10 was interested in this issue as well, would you like to work together on it?

**Comment by somya51p** [comment]
@jennydaman sure.

**Comment by sherrif10** [comment]
Let's catch up and do this together

**Comment by sherrif10** [comment]
Hey @somya51p  can we catch up tomorrow for this issue. Lets do it together , ping me on the chat please

**Comment by somya51p** [comment]
> Hey @somya51p can we catch up tomorrow for this issue. Lets do it together , ping me on the chat please

Surely!!

**Comment by jennydaman** [comment]
Happy that you two are choosing to work together!

**Comment by sherrif10** [comment]
Hello @somya51p . Let me know your availability please on matrix.

**Comment by somya51p** [comment]
@jennydaman It would be great if you could guide me on this issue.

**Comment by jennydaman** [comment]
https://github.com/FNNDSC/miniChRIS-docker/commit/e3ad9563bca9abc4aeb0a559598dd21a41151537
