### ISSUE TITLE
chris_store_ui container fails to start

### ISSUE THREAD

**Issue by qxprakash** [FNNDSC/miniChRIS#6]
recreating this issue is similiar to the , restarting of scheduler container issue , wherein if the container is stopped abruptly , say for e.g --docker kill (docker ps -q) , and after that if you start minichris again by ./minichris.sh , the chris_store_ui would not start 

**LOGS**
docker compose logs chris_store_ui

adduser: user 'chris' in use

**Comment by qxprakash** [comment]
just removing the chris_store_ui container , and then restarting docker compose , solves the problem..

**Comment by qxprakash** [comment]
@jennydaman this is happening in the docker-entrypoint.sh it is trying to add user but since , on killing the container user is not deleted , so trying to add user again while it already exists is causing this error , and preventing the container from being started !

**Comment by qxprakash** [comment]
@fortune-max we will have to make changes to the docker-entrypoint.sh , to bypass adding user if it already exists..

**Comment by fortune-max** [comment]
This is helpful, thank you

**Comment by qxprakash** [comment]
@jennydaman I closed the first pr #8  because , I was not on master branch which added extra commit of the previous issue , please look at the new one.. #9 thanks..

**Comment by jennydaman** [comment]
Fixed in https://github.com/FNNDSC/ChRIS_store_ui/commit/ea2f20012c5fc2a274045cc629ae0bfc18752a76
